name: OpenSSF Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: "23 7 * * 1"
  workflow_dispatch:

permissions: read-all

jobs:
  scorecard:
    name: Scorecard
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: read
      contents: read
      id-token: write
      issues: read
      pull-requests: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run OpenSSF Scorecard
        uses: ./.github/actions/run-scorecard
        with:
          upload-sarif: "true"
